### ISSUE TITLE
InputStream.toSyncStream has wrong return type

### ISSUE THREAD

**Issue by vanniktech** [korlibs/korlibs#186]
Should not `InputStream.toSyncStream()` return a `SyncStream` rather than a `SyncInputStream`? It seems off that both methods return the same type but have different functions.

<img width="626" alt="Screenshot 2024-08-15 at 16 29 22" src="https://github.com/user-attachments/assets/480bed53-9b9e-4b05-b1ef-0d03c5ce13a7">

**Comment by soywiz** [comment]
So basically toSyncStream was probably an old variant with the wrong naming. I have deprecated it.
The reason is that SyncStream in korlibs has seeking support, while InputStream not. The equivalent is InputSyncStream.
